### ISSUE TITLE
Feature request: sitemap index and multiple files when over 50K urls

### ISSUE THREAD

**Issue by pinmaster751** [tobiaskluge/phpsitemapng#4]
Is it possible to automatically create many sitemap files and sitemap-index for those files in case when there are over 50K urls ? Would be nice feature

**Comment by tobiaskluge** [comment]
@pinmaster751 
I created this script like 15 years ago while studying computer science and haven't touched it since then.
As far as I remember, the beta 1.6 was a complete rewrite that was exactly handling this issues. But it was not really finished and never was shipped as productive release.
Depending on your project, you might be better off writing a short, simple export script to XML Sitemaps with your CMS or web project - crawling external sites with 50k urls is a heavy load on the server that might not be necessary.
